// <auto-generated />
using System;
using MedicalJourneyLog.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedicalJourneyLog.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MedicalJourneyLog.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ChildId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Doctor")
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("MedicalJourneyLog.Models.Caregiver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Caregivers");
                });

            modelBuilder.Entity("MedicalJourneyLog.Models.CaregiverChild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CaregiverId")
                        .HasColumnType("int");

                    b.Property<int>("ChildId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CaregiverId");

                    b.HasIndex("ChildId");

                    b.ToTable("CaregiverChildren");
                });

            modelBuilder.Entity("MedicalJourneyLog.Models.Child", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Children");
                });

            modelBuilder.Entity("MedicalJourneyLog.Models.Milestone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ChildId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.ToTable("Milestones");
                });

            modelBuilder.Entity("MedicalJourneyLog.Models.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ChildId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("MedicalJourneyLog.Models.Symptom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ChildId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateLogged")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.ToTable("Symptoms");
                });

            modelBuilder.Entity("MedicalJourneyLog.Models.Appointment", b =>
                {
                    b.HasOne("MedicalJourneyLog.Models.Child", "Child")
                        .WithMany("Appointments")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("MedicalJourneyLog.Models.CaregiverChild", b =>
                {
                    b.HasOne("MedicalJourneyLog.Models.Caregiver", "Caregiver")
                        .WithMany("CaregiverChildren")
                        .HasForeignKey("CaregiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicalJourneyLog.Models.Child", "Child")
                        .WithMany("CaregiverChildren")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Caregiver");

                    b.Navigation("Child");
                });

            modelBuilder.Entity("MedicalJourneyLog.Models.Milestone", b =>
                {
                    b.HasOne("MedicalJourneyLog.Models.Child", "Child")
                        .WithMany("Milestones")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("MedicalJourneyLog.Models.Note", b =>
                {
                    b.HasOne("MedicalJourneyLog.Models.Child", "Child")
                        .WithMany("Notes")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("MedicalJourneyLog.Models.Symptom", b =>
                {
                    b.HasOne("MedicalJourneyLog.Models.Child", "Child")
                        .WithMany("Symptoms")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("MedicalJourneyLog.Models.Caregiver", b =>
                {
                    b.Navigation("CaregiverChildren");
                });

            modelBuilder.Entity("MedicalJourneyLog.Models.Child", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("CaregiverChildren");

                    b.Navigation("Milestones");

                    b.Navigation("Notes");

                    b.Navigation("Symptoms");
                });
#pragma warning restore 612, 618
        }
    }
}
